name: emailsender

on:
    push:
        branches: [ master ]

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout 
          uses: actions/checkout@v2 
  
        - name: Setup Python Version
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        - name: Execute script 
          run: python emailsender.py